<?php tiny::layout()->default(title: 'Terms &amp; Conditions', emptyLayout: false); ?>

<div id="main-content" class="relative z-10 bg-gradient-to-b from-indigo-50/5 via-white to-white min-h-screen ">
    <main x-class="mx-8 relative">
        <section class="pt-16 max-w-2xl mx-auto">
            <div>
                <h1 class="text-4xl font-semibold">Terms &amp; Conditions</h1>
                <p class="my-2 opacity-50">Last updated: Jan 2, 2024</p>

                <p class="my-4 text-[15px] text-slate-700">
                    THIS TERMS OF USE AGREEMENT (the “Agreement”) constitutes a legally binding agreement by and between Automaze, Ltd., a limited liability company organized under the laws of United Kingdom (“Automaze”) and the client, whether personally or on behalf of an entity (“Client”), with regard to access and use of Automaze’s website: 
                    <a class="text-blue-500 hover:underline" href="https://automaze.io">automaze.io</a>
                    (the “Website”) and any other media form, channel, mobile website or mobile application related, linked or otherwise connected thereto. Failure to agree and adhere to all of the terms, conditions and obligations contained herein results in the express prohibition of the Client’s use of the Website, and the Client is ordered to discontinue use immediately. Thereafter the relationship between Client and Automaze shall cease and be of no further force and effect between the parties, except that any obligation of Client to pay Automaze for services rendered shall remain and continue to be an ongoing obligation owed by Client to Automaze.
                </p>
                <h2 class="mt-6 font-bold">1. Intellectual Property Rights</h2>
                <p class="my-4 text-[15px] text-slate-700">Unless otherwise indicated, the Website is the property of Automaze and all source code, databases, functionality, software, website designs, audio, video, text, photographs and graphics of any nature and regardless of format (herein, collectively or individually, the “Content”) and the trademarks, service marks, and logos contained there (the “Marks”) are owned and controlled by Automaze and are protected by copyright and trademark laws of the United Kingdom and foreign countries. The Content and Marks are provided “As-Is” for your information and personal use only. Except as expressly provided herein, no part of the Website and no Content may be copied, reproduced, aggregated, republished, uploaded, posted, displayed, encoded, translated, transmitted, distributed, sold, licensed, or otherwise exploited for any commercial purpose whatsoever, without Automaze’s express prior written permission. Automaze reserves all rights in the Website, Content and Marks.</p>
                <h2 class="mt-6 font-bold">2. Ownership of Materials</h2>
                <p class="my-4 text-[15px] text-slate-700">Notwithstanding Automaze’s ownership of Submissions, as described in Paragraph 4 (“Client Feedback”), all tasks and original source files created on Client’s behalf (“Projects”) belong to Client, and Client shall be the sole owner of the copyright for all Projects. In the event that any operation of law would cause Automaze to become the owner of a Project, in whole or in part, rather than Client, Automaze irrevocably and perpetually assigns its entire interest in the Project to Client, without limitation. Client warrants that any and all materials provided to Automaze as examples or as material to be incorporated into a project during the relationship are owned by Client and do not infringe on or misappropriate any third party’s rights, including, but not limited to, all intellectual property rights and any right of publicity. Automaze always reserves the right to share the Client&#x27;s work publicy (social media, website, etc.) unless agreed upon as stated in section 18 of this document.</p>
                <h2 class="mt-6 font-bold">3. Third-Party Software</h2>
                <p class="my-4 text-[15px] text-slate-700">In the event that any Project incorporates software that is not owned by Automaze and require a commercial license in order for Client to legally reproduce, distribute, or publicly display the Project (“Third-Party Software”), Automaze will inform Client in writing that one or more Third-Party Software have been incorporated into the Project and that Client will need to purchase one or more licenses for the Third-Party Software from the rights-holder(s) of said Third Party Software in order to legally reproduce, distribute, or publicly display the Project. Said notice will include information sufficient for Client to identify which licenses are required and who to contact in order to purchase said licenses. So long as Automaze has informed Client of the incorporation of Third-Party Software as described above, Client assumes all responsibility for any consequences as a result of a failure by Client to purchase one or more licenses for any Third-Party Software incorporated into a Project.</p>
                <h2 class="mt-6 font-bold">4. User Representations</h2>
                <p class="my-4 text-[15px] text-slate-700">By using the Website, Client represents and warrants that: Client has the legal capacity and agrees to comply with these Terms of Use; Client is not a minor in the jurisdiction of their domicile; Client will not access the Website through automated or non-human means; Client will not use the Website for any illegal or unauthorized purpose; Client’s use of the Website will not violate any applicable law or regulation.</p>
                <h2 class="mt-6 font-bold">5. Prohibited Activities</h2>
                <p class="my-4 text-[15px] text-slate-700">Client shall not access or use the Website for any purpose other than that for which the Website is made available to the Client. The Website may not be used in connection with any commercial endeavors except those related to the work performed by Automaze on behalf of the Client. Further, Client agrees to refrain from the following: Make any unauthorized use of the Website; Retrieve data or content for the purposes of creating or compiling a database or directory; Circumvent, disable, or otherwise interfere with security-related features on the Website; Engage in unauthorized framing or linking of the Website; Trick, defraud or mislead Automaze or other users; Interfere with, disrupt or create an undue burden on the Website or Automaze’s networks or servers; Use the Website in an effort to compete with Automaze; Decipher, decompile, disassemble, or reverse engineer any of the software comprising or in any way making up a part of the Website; Bypass any measures on the Website designed to prevent or restrict access to the Website or any portion thereof; Harass, annoy, intimidate or threaten any of Automaze’s employees, independent contractors or agents providing services through the Website; Delete the copyright or other rights notice from any Content; Copy or adapt the Website’s softwareUpload or transmit, or attempt to do so, viruses, Trojan horses, or other material including anything that interferes with any party’s use of the Website or modifies, impairs, disrupts, alters, or interferes with the use, features, functions, operations or maintenance of the Website; Upload or transmit, or attempt to do so, any material that acts as a passive or active information collection or transmission mechanism; Disparage, tarnish or otherwise harm Automaze; Use the Website in a manner inconsistent with any applicable laws, statutes or regulations.</p>
                <h2 class="mt-6 font-bold">6. Client Feedback</h2>
                <p class="my-4 text-[15px] text-slate-700">Client acknowledges and agrees that any questions, comments, suggestions or other feedback or submission (each a “Submission”) shall be the sole property of Automaze and Automaze is under no obligation to keep a Submission confidential or take steps necessary to ensure the confidentiality of a Submission. Automaze shall be the sole and exclusive owner of all rights related to the Submission except to the extent that rights are granted to Client under Paragraph 2 (“Ownership of Materials”), and shall at its sole and unrestricted discretion use and disseminate a Submission for any lawful purpose without permission, acknowledgment or compensation of or to the Client. Client agrees that it has the right to articulate and put forth the Submission and Client hereby waives all claims and recourse against Automaze for its use of the Submission in accordance with the terms hereof and in its sole discretion hereafter.</p>
                <h2 class="mt-6 font-bold">7. Management and Oversite</h2>
                <p class="my-4 text-[15px] text-slate-700">Automaze reserves the right to monitor the Website for violations of these Terms of Use and to take appropriate legal action in response to a violation of the Terms of Use or any applicable law, statute or regulation. Automaze further reserves the right to restrict or deny access to the Website or disable the Client’s use of the Website. Such decision shall be in the sole discretion of Automaze, without notice or liability to Client. All decisions regarding the management of the Website shall be at the sole discretion of Automaze and shall be designed to protect Automaze’s rights and property.</p>
                <h2 class="mt-6 font-bold">8. Privacy Policy</h2>
                <p class="my-4 text-[15px] text-slate-700">
                    By using the Website, Client agrees to be bound and abide by the
                    <a href="https://www.notion.so/Privacy-Policy-2463d3b5f47e4fc5b3033f98ec3219b5?pvs=21">Privacy Policy</a>
                    and the terms more particularly set forth therein and adopted and incorporated herein. The Website is hosted in the United Kingdom. Access of the Website from the United States, Asia or other region of the world may result in the applicability of laws, statutes or regulations differing from those of the United Kingdom which govern personal data collection, use or disclosure. Client’s continued use of the Website and transfer of data to the United Kingdom constitutes express consent of Client to the transfer and processing of data in the United Kingdom. Automaze does not knowingly accept or solicit information from individuals under the age of 18. In accordance with the United Kingdom’ laws, upon the receipt of actual knowledge that an individual under the age of 13 has provided personally identifiable information to Automaze without parental consent, Automaze shall delete that information as soon as reasonably practical.
                </p>
                <h2 class="mt-6 font-bold">9. Returns and Refunds</h2>
                <p class="my-4 text-[15px] text-slate-700">Automaze reserves the right to deny refunds based on its own self discretion and without notice or liability to Client. Refund requests are assessed on a case by case basis. Should Client request a refund during the first month of use, all materials produced by Automaze are ownership of the company and are prohibited from being used by the Client in any way. If a refund is deemed to be appropriate, there will be a 25% fee assigned to the remaining billable period. Automaze reserves the right to take appropriate legal actions against Client for breach of this paragraph.</p>
                <h2 class="mt-6 font-bold">10. Modification</h2>
                <p class="my-4 text-[15px] text-slate-700">Automaze reserves the right to change, alter, modify, amend or remove anything or any content on the Website for any reason at its sole discretion. Automaze reserves the right to modify or discontinue all or part of the Website without notice and without liability to Client.</p>
                <h2 class="mt-6 font-bold">11. Connection Interruptions</h2>
                <p class="my-4 text-[15px] text-slate-700">Automaze does not guaranty or warrant the Website will be available and accessible at all times. Issues with hardware, software or other items may result in interruption delays or errors beyond Automaze’s control. Client agrees that Automaze shall not be liable to Client for any loss, damage or inconvenience caused by Client’s inability to access or use the Website during any interruption in the connection or service.</p>
                <h2 class="mt-6 font-bold">12. Governing Law</h2>
                <p class="my-4 text-[15px] text-slate-700">These Terms of Use shall be governed by and construed in accordance with the laws of the United Kingdom without regard to conflict of law principals.</p>
                <h2 class="mt-6 font-bold">13. Litigation</h2>
                <p class="my-4 text-[15px] text-slate-700">Any legal action of whatever nature shall be brought in the courts of London, United Kingdom. The parties hereto consent to personal jurisdiction in said courts and waive all defenses of lack of personal jurisdiction and forum non conveniens with respect to venue and jurisdiction. Application of the United Nations Convention on Contracts for the International Sale of Goods and the Uniform Computer Information Transaction Act are excluded from these Terms of Use.</p>
                <h2 class="mt-6 font-bold">14. Disclaimer</h2>
                <p class="my-4 text-[15px] text-slate-700">THE WEBSITE IS PROVIDED ON AN AS-IS, AS-AVAILABLE BASIS. CLIENT AGREES THAT ITS USE OF THE WEBSITE AND SERVICES ARE AT CLIENT’S SOLE RISK. AUTOMAZE DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE WEBSITE AND CLIENT’S USE THEREOF, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. AUTOMAZE MAKES NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THE WEBSITE OR ANY CONTENT THEREON OR CONTENT OF ANY WEBSITES LINKED TO THE WEBSITE AND AUTOMAZE ASSUMES NO LIABILITY FOR ANY ERRORS, MISTAKES OR INACCURACIES OF CONTENT AND MATERIALS, PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, ANY UNAUTHORIZED ACCESS TO OR USE OF AUTOMAZE’S SECURE SERVERS AND/OR ANY PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SITE, ANY BUGS, VIRUSES, TROJAN HORSES OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE WEBSITE BY ANY THIRD PARTY AND/OR ANY ERRORS OR OMISSIONS IN CONTENT AND MATERIALS OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, TRANSMITTED OR OTHERWISE MADE AVAILABLE THROUGH THE WEBSITE. AUTOMAZE DOES NOT WARRANT, ENDORSE, GUARANTEE OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY EITHER THROUGH THE WEBSITE, A HYPERLINKED WEBSITE OR ANY WEBSITE OR MOBILE APPLICATION FEATURED IN ANY ADVERTISING.</p>
                <h2 class="mt-6 font-bold">15. Limitations of Liability and Indemnification</h2>
                <p class="my-4 text-[15px] text-slate-700">Automaze and its directors, employees, members, independent contractors or agents shall not be liable to Client or any third party for any direct, indirect, consequential, incidental, special or punitive damages, including lost profit, lost revenue, lost data, attorneys’ fees, court costs, fines, forfeitures or other damages or losses arising from Client’s use of the Website.Client agrees to defend, indemnify and hold harmless, Automaze and its subsidiaries, affiliates and all respective officers, members, agents, partners, employees and independent contractors from and against any loss, damage, liability, claim or demand including reasonable attorneys’ fees and expenses, made by any third party due to or arising out of: (1) use of the Website; (2) breach of these Terms of Use; (3) any breach of Client’s representations and warranties set forth herein; (4) Client’s violation of the rights of any third party, including but not limited to intellectual property rights. Notwithstanding the foregoing, Automaze reserves the right, at Client’s expense, to assume control and defense of any matter for which Client shall be required to indemnify Automazehereunder. Client agrees to cooperate with the defense of such claims.</p>
                <h2 class="mt-6 font-bold">16. User Data</h2>
                <p class="my-4 text-[15px] text-slate-700">Client is solely responsible for all data transmitted to or that relates to any activity Client has undertaken using the Website. Automaze shall have no liability to Client for any loss or corruption of any such data and Client hereby waives any right of action against Automaze from any such loss or corruption.</p>
                <h2 class="mt-6 font-bold">17. Electronic communications, transactions and signatures</h2>
                <p class="my-4 text-[15px] text-slate-700">Client hereby consents to receive electronic communications from Automaze and Client agrees that all agreements, notices, disclosures and other communications sent via email or through the Website satisfy any legal requirement that such communication be in writing. Client hereby agrees to the use of electronic signatures, contracts, orders and other records, and to electronic delivery of notices, policies and records of transactions initiated or completed by Automaze or through the Website. Client hereby waives any rights or requirements under any statutes, regulations, rules, ordinances or other laws in any jurisdiction which require an original signature or delivery or retention of non-electronic records or to payments or the granting of credits by any means other than electronic.</p>
                <h2 class="mt-6 font-bold">18. Showcasing Work</h2>
                <p class="my-4 text-[15px] text-slate-700">Automaze reserves to right to share work on digital channels including social media, website, etc. unless otherwise agreed upon. The Client reserves the right to issue an NDA between themselves and Automaze, which in turn would void the right of Automaze to share or discuss Client&#x27;s work publicly.</p>
                <h2 class="mt-6 font-bold">19. Miscellaneous</h2>
                <p class="my-4 text-[15px] text-slate-700">These Terms of Use and any policies posted on the Website or regarding the Website constitute the entire agreement and understanding between the Client and Automaze. Failure of Automaze to enforce any right or provision of these Terms of Use shall not operate as a waiver of such right or provision. If any provision or part of these Terms of Use is determined to be unlawful, void or unenforceable, that provision shall be severed from these Terms of Use but shall not otherwise affect the validity or unenforceability of the remaining provisions herein. Nothing in these Terms of Use, the Privacy Policy or on the Website shall be construed to constitute the forming of a joint venture, partnership, employment or agency relationship between Client and Automaze.</p>
                <h2 class="mt-6 font-bold">20. Contact Information</h2>
                <p class="my-4 text-[15px] text-slate-700">
                    For any questions or complaints regarding the Website, please contact Automaze at:
                    <a class="text-blue-500 hover:underline" href="mailto:hello@automaze.io">hello@automaze.io</a>.
                </p>
            </div>
        </section>
    </main>
</div>


<?php tiny::layout()->default('/'); ?>
