<?php header('Content-Type: text/xml'); ?>
<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>https://automaze.io</loc>
        <lastmod>2025-09-03</lastmod>
        <changefreq>weekly</changefreq>
        <priority>1.0</priority>
    </url>
    <url>
        <loc>https://automaze.io/about</loc>
        <lastmod>2025-09-03</lastmod>
        <changefreq>weekly</changefreq>
        <priority>1.0</priority>
    </url>
    <url>
        <loc>https://automaze.io/services</loc>
        <lastmod>2025-09-03</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://automaze.io/services/cto-as-a-service</loc>
        <lastmod>2025-09-03</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://automaze.io/services/mvp-launch</loc>
        <lastmod>2025-09-03</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://automaze.io/services/managed-developers</loc>
        <lastmod>2025-09-03</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://automaze.io/services/ai-agents</loc>
        <lastmod>2025-09-03</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://automaze.io/services/design-subscription</loc>
        <lastmod>2025-09-03</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://automaze.io/discovery-call</loc>
        <lastmod>2025-09-03</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://automaze.io/services/devops-optimization</loc>
        <lastmod>2025-09-03</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://automaze.io/pricing</loc>
        <lastmod>2025-09-03</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.5</priority>
    </url>
    <url>
        <loc>https://automaze.io/legal/privacy</loc>
        <lastmod>2025-09-03</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.5</priority>
    </url>
    <url>
        <loc>https://automaze.io/legal/terms</loc>
        <lastmod>2025-09-03</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.5</priority>
    </url>
</urlset>

